-- DEPOC-13: Streamline Customer Information Collection and Verification
-- Tables: STG_CUSTOMER_ONBOARDING, CUSTOMER_ONBOARDING, ONBOARDING_AUDIT_LOG

CREATE OR REPLACE TABLE DE_POC.PUBLIC.STG_CUSTOMER_ONBOARDING (
    APPLICATION_ID VARCHAR(50) NOT NULL,
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    EMAIL VARCHAR(255),
    PHONE VARCHAR(50),
    ADDRESS VARCHAR(500),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    COUNTRY VARCHAR(100),
    DATE_OF_BIRTH VARCHAR(20),
    ID_DOCUMENT_TYPE VARCHAR(50),
    ID_DOCUMENT_NUMBER VARCHAR(100),
    SUBMITTED_AT VARCHAR(50),
    ROW_NUM NUMBER(38,0) AUTOINCREMENT START 1 INCREMENT 1,
    _BATCH_ID VARCHAR(100),
    _LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
) COMMENT = 'DEPOC-13: Staging table for raw customer onboarding application submissions';

CREATE OR REPLACE TABLE DE_POC.PUBLIC.CUSTOMER_ONBOARDING (
    APPLICATION_ID VARCHAR(50) NOT NULL,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PHONE VARCHAR(50),
    ADDRESS VARCHAR(500),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    COUNTRY VARCHAR(100) NOT NULL,
    DATE_OF_BIRTH DATE,
    ID_DOCUMENT_TYPE VARCHAR(50),
    ID_DOCUMENT_NUMBER VARCHAR(100),
    VERIFICATION_STATUS VARCHAR(20) DEFAULT 'PENDING',
    VERIFICATION_TIMESTAMP TIMESTAMP_NTZ,
    VERIFICATION_DETAILS VARIANT,
    APPROVAL_STATUS VARCHAR(20) DEFAULT 'PENDING',
    APPROVAL_TIMESTAMP TIMESTAMP_NTZ,
    ESIGNATURE_STATUS VARCHAR(20) DEFAULT 'NOT_REQUIRED',
    ESIGNATURE_TIMESTAMP TIMESTAMP_NTZ,
    CRM_STATUS VARCHAR(20) DEFAULT 'NOT_SYNCED',
    CRM_SYNC_TIMESTAMP TIMESTAMP_NTZ,
    ONBOARDING_STATUS VARCHAR(20) DEFAULT 'IN_PROGRESS',
    SUBMITTED_AT TIMESTAMP_NTZ,
    COMPLETED_AT TIMESTAMP_NTZ,
    _BATCH_ID VARCHAR(100),
    _INSERTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    _UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_CUSTOMER_ONBOARDING PRIMARY KEY (APPLICATION_ID)
) COMMENT = 'DEPOC-13: Target table for customer onboarding workflow';

CREATE OR REPLACE TABLE DE_POC.PUBLIC.ONBOARDING_AUDIT_LOG (
    LOG_ID NUMBER(38,0) AUTOINCREMENT START 1 INCREMENT 1,
    APPLICATION_ID VARCHAR(50) NOT NULL,
    EVENT_TYPE VARCHAR(50) NOT NULL,
    EVENT_STATUS VARCHAR(20) NOT NULL,
    EVENT_DETAILS VARIANT,
    BATCH_ID VARCHAR(100),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
) COMMENT = 'DEPOC-13: Audit log for all onboarding workflow events';
