-- DEPOC-13: Main onboarding pipeline procedure
-- Handles: AC-1 (verification), AC-2 (approval), AC-3 (e-signature initiation)

CREATE OR REPLACE PROCEDURE DE_POC.PUBLIC.SP_ONBOARD_CUSTOMER(P_BATCH_ID VARCHAR DEFAULT NULL)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
BEGIN
    LET v_batch_id VARCHAR := COALESCE(:P_BATCH_ID, 'BATCH_' || TO_VARCHAR(CURRENT_TIMESTAMP(), 'YYYYMMDD_HH24MISS'));
    LET v_total_staged INTEGER := 0;
    LET v_verified INTEGER := 0;
    LET v_failed_verification INTEGER := 0;
    LET v_approved INTEGER := 0;

    SELECT COUNT(*) INTO :v_total_staged FROM DE_POC.PUBLIC.STG_CUSTOMER_ONBOARDING WHERE _BATCH_ID IS NULL OR _BATCH_ID = '';

    IF (:v_total_staged = 0) THEN
        RETURN OBJECT_CONSTRUCT('status', 'NO_DATA', 'message', 'No new records in staging table', 'batch_id', :v_batch_id);
    END IF;

    BEGIN TRANSACTION;

    UPDATE DE_POC.PUBLIC.STG_CUSTOMER_ONBOARDING SET _BATCH_ID = :v_batch_id WHERE _BATCH_ID IS NULL OR _BATCH_ID = '';

    -- AC-1: Real-time verification via MERGE
    MERGE INTO DE_POC.PUBLIC.CUSTOMER_ONBOARDING AS tgt
    USING (
        SELECT APPLICATION_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, ADDRESS, CITY, STATE, COUNTRY,
            TRY_TO_DATE(DATE_OF_BIRTH, 'YYYY-MM-DD') AS DATE_OF_BIRTH,
            ID_DOCUMENT_TYPE, ID_DOCUMENT_NUMBER,
            TRY_TO_TIMESTAMP_NTZ(SUBMITTED_AT) AS SUBMITTED_AT,
            CASE
                WHEN EMAIL IS NULL OR EMAIL = '' OR NOT REGEXP_LIKE(EMAIL, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$') THEN 'FAILED'
                WHEN FIRST_NAME IS NULL OR FIRST_NAME = '' THEN 'FAILED'
                WHEN LAST_NAME IS NULL OR LAST_NAME = '' THEN 'FAILED'
                WHEN COUNTRY IS NULL OR COUNTRY = '' THEN 'FAILED'
                WHEN ID_DOCUMENT_NUMBER IS NULL OR ID_DOCUMENT_NUMBER = '' THEN 'FAILED'
                ELSE 'VERIFIED'
            END AS VERIF_STATUS,
            CASE
                WHEN EMAIL IS NULL OR EMAIL = '' OR NOT REGEXP_LIKE(EMAIL, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$') THEN 'Invalid email'
                WHEN FIRST_NAME IS NULL OR FIRST_NAME = '' THEN 'Missing first name'
                WHEN LAST_NAME IS NULL OR LAST_NAME = '' THEN 'Missing last name'
                WHEN COUNTRY IS NULL OR COUNTRY = '' THEN 'Missing country'
                WHEN ID_DOCUMENT_NUMBER IS NULL OR ID_DOCUMENT_NUMBER = '' THEN 'Missing ID document'
                ELSE 'All checks passed'
            END AS VERIF_DETAIL
        FROM DE_POC.PUBLIC.STG_CUSTOMER_ONBOARDING WHERE _BATCH_ID = :v_batch_id
    ) AS src
    ON tgt.APPLICATION_ID = src.APPLICATION_ID
    WHEN MATCHED THEN UPDATE SET
        tgt.FIRST_NAME = src.FIRST_NAME, tgt.LAST_NAME = src.LAST_NAME, tgt.EMAIL = src.EMAIL,
        tgt.PHONE = src.PHONE, tgt.ADDRESS = src.ADDRESS, tgt.CITY = src.CITY,
        tgt.STATE = src.STATE, tgt.COUNTRY = src.COUNTRY, tgt.DATE_OF_BIRTH = src.DATE_OF_BIRTH,
        tgt.ID_DOCUMENT_TYPE = src.ID_DOCUMENT_TYPE, tgt.ID_DOCUMENT_NUMBER = src.ID_DOCUMENT_NUMBER,
        tgt.VERIFICATION_STATUS = src.VERIF_STATUS, tgt.VERIFICATION_TIMESTAMP = CURRENT_TIMESTAMP(),
        tgt.VERIFICATION_DETAILS = OBJECT_CONSTRUCT('detail', src.VERIF_DETAIL),
        tgt.ESIGNATURE_STATUS = CASE WHEN src.VERIF_STATUS = 'VERIFIED' THEN tgt.ESIGNATURE_STATUS ELSE 'NOT_REQUIRED' END,
        tgt._BATCH_ID = :v_batch_id, tgt._UPDATED_AT = CURRENT_TIMESTAMP()
    WHEN NOT MATCHED THEN INSERT (
        APPLICATION_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, ADDRESS, CITY, STATE, COUNTRY,
        DATE_OF_BIRTH, ID_DOCUMENT_TYPE, ID_DOCUMENT_NUMBER,
        VERIFICATION_STATUS, VERIFICATION_TIMESTAMP, VERIFICATION_DETAILS,
        APPROVAL_STATUS, ESIGNATURE_STATUS, CRM_STATUS, ONBOARDING_STATUS,
        SUBMITTED_AT, _BATCH_ID, _INSERTED_AT, _UPDATED_AT
    ) VALUES (
        src.APPLICATION_ID, src.FIRST_NAME, src.LAST_NAME, src.EMAIL, src.PHONE, src.ADDRESS,
        src.CITY, src.STATE, src.COUNTRY, src.DATE_OF_BIRTH, src.ID_DOCUMENT_TYPE, src.ID_DOCUMENT_NUMBER,
        src.VERIF_STATUS, CURRENT_TIMESTAMP(), OBJECT_CONSTRUCT('detail', src.VERIF_DETAIL),
        CASE WHEN src.VERIF_STATUS = 'VERIFIED' THEN 'PENDING' ELSE 'BLOCKED' END,
        CASE WHEN src.VERIF_STATUS = 'VERIFIED' THEN 'PENDING_SIGNATURE' ELSE 'NOT_REQUIRED' END,
        'NOT_SYNCED',
        CASE WHEN src.VERIF_STATUS = 'VERIFIED' THEN 'IN_PROGRESS' ELSE 'FAILED' END,
        src.SUBMITTED_AT, :v_batch_id, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
    );

    COMMIT;

    SELECT COUNT(*) INTO :v_verified FROM DE_POC.PUBLIC.CUSTOMER_ONBOARDING WHERE _BATCH_ID = :v_batch_id AND VERIFICATION_STATUS = 'VERIFIED';
    SELECT COUNT(*) INTO :v_failed_verification FROM DE_POC.PUBLIC.CUSTOMER_ONBOARDING WHERE _BATCH_ID = :v_batch_id AND VERIFICATION_STATUS = 'FAILED';

    INSERT INTO DE_POC.PUBLIC.ONBOARDING_AUDIT_LOG (APPLICATION_ID, EVENT_TYPE, EVENT_STATUS, EVENT_DETAILS, BATCH_ID)
    SELECT APPLICATION_ID, 'VERIFICATION', VERIFICATION_STATUS, VERIFICATION_DETAILS, :v_batch_id
    FROM DE_POC.PUBLIC.CUSTOMER_ONBOARDING WHERE _BATCH_ID = :v_batch_id;

    -- AC-2: Auto-approve verified records
    UPDATE DE_POC.PUBLIC.CUSTOMER_ONBOARDING
    SET APPROVAL_STATUS = 'APPROVED', APPROVAL_TIMESTAMP = CURRENT_TIMESTAMP(), ONBOARDING_STATUS = 'PENDING_SIGNATURE'
    WHERE _BATCH_ID = :v_batch_id AND VERIFICATION_STATUS = 'VERIFIED' AND APPROVAL_STATUS = 'PENDING';

    SELECT COUNT(*) INTO :v_approved FROM DE_POC.PUBLIC.CUSTOMER_ONBOARDING WHERE _BATCH_ID = :v_batch_id AND APPROVAL_STATUS = 'APPROVED';

    INSERT INTO DE_POC.PUBLIC.ONBOARDING_AUDIT_LOG (APPLICATION_ID, EVENT_TYPE, EVENT_STATUS, EVENT_DETAILS, BATCH_ID)
    SELECT APPLICATION_ID, 'APPROVAL', 'APPROVED', OBJECT_CONSTRUCT('approved_by', 'SYSTEM_AUTO', 'sla_hours', 0), :v_batch_id
    FROM DE_POC.PUBLIC.CUSTOMER_ONBOARDING WHERE _BATCH_ID = :v_batch_id AND APPROVAL_STATUS = 'APPROVED';

    -- AC-3: E-signature pending for approved records
    INSERT INTO DE_POC.PUBLIC.ONBOARDING_AUDIT_LOG (APPLICATION_ID, EVENT_TYPE, EVENT_STATUS, EVENT_DETAILS, BATCH_ID)
    SELECT APPLICATION_ID, 'ESIGNATURE', 'PENDING_SIGNATURE', OBJECT_CONSTRUCT('method', 'ELECTRONIC', 'sent_at', CURRENT_TIMESTAMP()::VARCHAR), :v_batch_id
    FROM DE_POC.PUBLIC.CUSTOMER_ONBOARDING WHERE _BATCH_ID = :v_batch_id AND APPROVAL_STATUS = 'APPROVED';

    RETURN OBJECT_CONSTRUCT('status', 'SUCCESS', 'batch_id', :v_batch_id, 'total_staged', :v_total_staged, 'verified', :v_verified, 'failed_verification', :v_failed_verification, 'approved', :v_approved, 'message', 'Onboarding pipeline completed successfully.');

EXCEPTION
    WHEN OTHER THEN
        ROLLBACK;
        INSERT INTO DE_POC.PUBLIC.ONBOARDING_AUDIT_LOG (APPLICATION_ID, EVENT_TYPE, EVENT_STATUS, EVENT_DETAILS, BATCH_ID)
        VALUES ('SYSTEM', 'PIPELINE_ERROR', 'ERROR', OBJECT_CONSTRUCT('error_code', SQLCODE, 'error_message', SQLERRM), :v_batch_id);
        RETURN OBJECT_CONSTRUCT('status', 'ERROR', 'batch_id', :v_batch_id, 'error_code', SQLCODE, 'error_message', SQLERRM);
END;
$$;
