-- DEPOC-13: CRM Sync procedure
-- Handles: AC-4 (update customer status in CRM on completion)

CREATE OR REPLACE PROCEDURE DE_POC.PUBLIC.SP_COMPLETE_ONBOARDING_CRM_SYNC()
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
BEGIN
    LET v_synced INTEGER := 0;

    -- AC-4: Complete e-signature and sync to CRM
    UPDATE DE_POC.PUBLIC.CUSTOMER_ONBOARDING
    SET ESIGNATURE_STATUS = 'SIGNED',
        ESIGNATURE_TIMESTAMP = CURRENT_TIMESTAMP(),
        CRM_STATUS = 'SYNCED',
        CRM_SYNC_TIMESTAMP = CURRENT_TIMESTAMP(),
        ONBOARDING_STATUS = 'COMPLETED',
        COMPLETED_AT = CURRENT_TIMESTAMP(),
        _UPDATED_AT = CURRENT_TIMESTAMP()
    WHERE APPROVAL_STATUS = 'APPROVED'
      AND ESIGNATURE_STATUS = 'PENDING_SIGNATURE'
      AND CRM_STATUS = 'NOT_SYNCED';

    SELECT COUNT(*) INTO :v_synced
    FROM DE_POC.PUBLIC.CUSTOMER_ONBOARDING
    WHERE CRM_STATUS = 'SYNCED' AND ONBOARDING_STATUS = 'COMPLETED'
      AND COMPLETED_AT >= DATEADD('minute', -5, CURRENT_TIMESTAMP());

    -- Audit: log CRM sync events (anti-duplicate guard)
    INSERT INTO DE_POC.PUBLIC.ONBOARDING_AUDIT_LOG (APPLICATION_ID, EVENT_TYPE, EVENT_STATUS, EVENT_DETAILS, BATCH_ID)
    SELECT c.APPLICATION_ID, 'CRM_SYNC', 'SYNCED',
           OBJECT_CONSTRUCT('crm_system', 'INTERNAL_CRM', 'synced_at', CURRENT_TIMESTAMP()::VARCHAR),
           c._BATCH_ID
    FROM DE_POC.PUBLIC.CUSTOMER_ONBOARDING c
    WHERE c.CRM_STATUS = 'SYNCED' AND c.COMPLETED_AT >= DATEADD('minute', -5, CURRENT_TIMESTAMP())
      AND NOT EXISTS (
          SELECT 1 FROM DE_POC.PUBLIC.ONBOARDING_AUDIT_LOG a
          WHERE a.APPLICATION_ID = c.APPLICATION_ID AND a.EVENT_TYPE = 'CRM_SYNC'
      );

    RETURN OBJECT_CONSTRUCT('status', 'SUCCESS', 'records_synced_to_crm', :v_synced, 'message', 'CRM sync completed. Customer onboarding status updated.');
EXCEPTION
    WHEN OTHER THEN
        RETURN OBJECT_CONSTRUCT('status', 'ERROR', 'error_code', SQLCODE, 'error_message', SQLERRM);
END;
$$;
