-- DEPOC-46 AC-7: Add GEOGRAPHY attribute to customer pipeline
-- Co-authored with CoCo

-- Add GEOGRAPHY to staging table
ALTER TABLE DE_POC.PUBLIC.RAW_CUSTOMERS ADD COLUMN IF NOT EXISTS GEOGRAPHY VARCHAR(200);

-- Add GEOGRAPHY to target table
ALTER TABLE DE_POC.PUBLIC.CUSTOMERS ADD COLUMN IF NOT EXISTS GEOGRAPHY VARCHAR(200);

-- Backfill GEOGRAPHY for existing records based on country
UPDATE DE_POC.PUBLIC.CUSTOMERS
SET GEOGRAPHY = CASE 
    WHEN COUNTRY = 'US' THEN 'North America'
    WHEN COUNTRY IN ('CA', 'MX') THEN 'North America'
    WHEN COUNTRY IN ('GB', 'DE', 'FR', 'IT', 'ES') THEN 'Europe'
    WHEN COUNTRY IN ('CN', 'JP', 'IN', 'KR', 'AU', 'NZ', 'SG') THEN 'Asia Pacific'
    ELSE 'Other'
END
WHERE GEOGRAPHY IS NULL;

-- Drop orphaned tables from prior iteration (Lead Issue #2)
DROP TABLE IF EXISTS DE_POC.PUBLIC.CUSTOMER;
DROP TABLE IF EXISTS DE_POC.PUBLIC.RAW_CUSTOMER_STAGING;
DROP TABLE IF EXISTS DE_POC.PUBLIC.CUSTOMER_LOAD_TRACKING;
DROP TABLE IF EXISTS DE_POC.PUBLIC.CUSTOMER_ERROR_LOG;

-- Recreate V_CUSTOMER_CURRENT with GEOGRAPHY (AC-7)
CREATE OR REPLACE VIEW DE_POC.PUBLIC.V_CUSTOMER_CURRENT
COMMENT = 'Downstream consumer view with geography. Supports AC-6 and AC-7 of DEPOC-46.'
AS
SELECT
    c.CUSTOMER_ID, c.FIRST_NAME, c.LAST_NAME, c.EMAIL, c.PHONE,
    c.ADDRESS, c.CITY, c.STATE, c.POSTAL_CODE, c.COUNTRY, c.GEOGRAPHY,
    c.CREATED_DATE, c.UPDATED_DATE, c._INSERTED_AT, c._UPDATED_AT,
    lt.SOURCE_FILE AS LAST_SOURCE_FILE,
    lt.LOAD_TIMESTAMP AS LAST_LOAD_TIMESTAMP,
    lt.STATUS AS LAST_LOAD_STATUS
FROM DE_POC.PUBLIC.CUSTOMERS c
LEFT JOIN DE_POC.PUBLIC.PIPELINE_LOAD_TRACKING lt ON c._LOAD_ID = lt.LOAD_ID;