-- DEPOC-3: Unit tests and data-quality validation for customer ingestion pipeline
-- Co-authored with CoCo
--
-- Run after executing SP_INGEST_CUSTOMERS or SP_INGEST_CUSTOMERS_FROM_STAGING
-- Expected: All tests return PASS

-- UT-01: Valid record count
SELECT 'UT-01' AS test, CASE WHEN COUNT(*) = 5 THEN 'PASS' ELSE 'FAIL' END AS result FROM DE_POC.PUBLIC.CUSTOMERS;

-- UT-02: Invalid records logged
SELECT 'UT-02' AS test, CASE WHEN COUNT(*) = 5 THEN 'PASS' ELSE 'FAIL' END AS result FROM DE_POC.PUBLIC.CUSTOMER_INGESTION_LOG WHERE SEVERITY = 'ERROR';

-- UT-03: Email normalization
SELECT 'UT-03' AS test, CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS result FROM DE_POC.PUBLIC.CUSTOMERS WHERE EMAIL != LOWER(EMAIL);

-- UT-04: No NULLs in required fields
SELECT 'UT-04' AS test, CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS result FROM DE_POC.PUBLIC.CUSTOMERS WHERE CUSTOMER_ID IS NULL OR FIRST_NAME IS NULL OR LAST_NAME IS NULL OR EMAIL IS NULL;

-- UT-05: No duplicate keys
SELECT 'UT-05' AS test, CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS result FROM (SELECT CUSTOMER_ID FROM DE_POC.PUBLIC.CUSTOMERS GROUP BY CUSTOMER_ID HAVING COUNT(*) > 1);

-- UT-06: Email format valid
SELECT 'UT-06' AS test, CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS result FROM DE_POC.PUBLIC.CUSTOMERS WHERE NOT CONTAINS(EMAIL, '@');

-- UT-07: Error reasons populated
SELECT 'UT-07' AS test, CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS result FROM DE_POC.PUBLIC.CUSTOMER_INGESTION_LOG WHERE SEVERITY = 'ERROR' AND (ERROR_REASON IS NULL OR ERROR_REASON = '');

-- DQ-01: Row reconciliation
SELECT 'DQ-01' AS test, CASE WHEN (SELECT COUNT(*) FROM DE_POC.PUBLIC.STG_CUSTOMERS) = (SELECT COUNT(*) FROM DE_POC.PUBLIC.CUSTOMERS) + (SELECT COUNT(*) FROM DE_POC.PUBLIC.CUSTOMER_INGESTION_LOG WHERE SEVERITY = 'ERROR') THEN 'PASS' ELSE 'FAIL' END AS result;
