-- DEPOC-5: Customer Data Ingestion and Validation Pipeline (V2)
-- Co-authored with CoCo
--
-- Features: Automated ingestion, field validation, quarantine, duplicate detection,
--           idempotent MERGE, full audit trail, restartability
--
-- Objects:
--   LOAD_TRACKING, STG_CUSTOMERS_V2, QUARANTINE_CUSTOMERS, CUSTOMERS_V2, PIPELINE_AUDIT_LOG
--   SP_INGEST_CUSTOMERS_V2(P_SOURCE_FILE)

CREATE OR REPLACE TABLE DE_POC.PUBLIC.LOAD_TRACKING (
  LOAD_ID NUMBER AUTOINCREMENT, FILE_NAME VARCHAR(500) NOT NULL, BATCH_ID VARCHAR(50) NOT NULL,
  LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(), ROW_COUNT INTEGER,
  STATUS VARCHAR(20) DEFAULT 'LOADED', CONSTRAINT UQ_LOAD_FILE UNIQUE (FILE_NAME)
);

CREATE OR REPLACE TABLE DE_POC.PUBLIC.STG_CUSTOMERS_V2 (
  ROW_NUM NUMBER AUTOINCREMENT, CUSTOMER_ID VARCHAR(50), FIRST_NAME VARCHAR(100),
  LAST_NAME VARCHAR(100), EMAIL VARCHAR(255), PHONE VARCHAR(50), ADDRESS VARCHAR(500),
  CITY VARCHAR(100), STATE VARCHAR(100), COUNTRY VARCHAR(100), CREATED_DATE VARCHAR(50),
  _LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(), _SOURCE_FILE VARCHAR(500), _BATCH_ID VARCHAR(50)
);

CREATE OR REPLACE TABLE DE_POC.PUBLIC.QUARANTINE_CUSTOMERS (
  QUARANTINE_ID NUMBER AUTOINCREMENT, BATCH_ID VARCHAR(50), CUSTOMER_ID VARCHAR(50),
  FIRST_NAME VARCHAR(100), LAST_NAME VARCHAR(100), EMAIL VARCHAR(255), PHONE VARCHAR(50),
  ADDRESS VARCHAR(500), CITY VARCHAR(100), STATE VARCHAR(100), COUNTRY VARCHAR(100),
  CREATED_DATE VARCHAR(50), REJECTION_REASON VARCHAR(1000), REJECTION_RULE VARCHAR(100),
  SOURCE_FILE VARCHAR(500), QUARANTINED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE DE_POC.PUBLIC.CUSTOMERS_V2 (
  CUSTOMER_ID VARCHAR(50) NOT NULL, FIRST_NAME VARCHAR(100) NOT NULL,
  LAST_NAME VARCHAR(100) NOT NULL, EMAIL VARCHAR(255) NOT NULL,
  PHONE VARCHAR(50), ADDRESS VARCHAR(500), CITY VARCHAR(100), STATE VARCHAR(100),
  COUNTRY VARCHAR(100), CREATED_DATE DATE,
  _INSERTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  _UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  _SOURCE_FILE VARCHAR(500), _BATCH_ID VARCHAR(50),
  CONSTRAINT PK_CUSTOMERS_V2 PRIMARY KEY (CUSTOMER_ID)
);

CREATE OR REPLACE TABLE DE_POC.PUBLIC.PIPELINE_AUDIT_LOG (
  LOG_ID NUMBER AUTOINCREMENT, LOG_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  BATCH_ID VARCHAR(50), PIPELINE_NAME VARCHAR(100) DEFAULT 'CUSTOMER_INGESTION_V2',
  ISSUE_KEY VARCHAR(20) DEFAULT 'DEPOC-5', PHASE VARCHAR(50), SEVERITY VARCHAR(10),
  MESSAGE VARCHAR(2000), DETAILS VARIANT, SOURCE_FILE VARCHAR(500)
);
