-- DEPOC-5: Unit tests and DQ validation for customer ingestion V2
-- Co-authored with CoCo
-- All tests should return PASS

SELECT 'UT-01: Target count' AS test, CASE WHEN COUNT(*) = 5 THEN 'PASS' ELSE 'FAIL' END FROM DE_POC.PUBLIC.CUSTOMERS_V2;
SELECT 'UT-02: Quarantine count' AS test, CASE WHEN COUNT(*) = 7 THEN 'PASS' ELSE 'FAIL' END FROM DE_POC.PUBLIC.QUARANTINE_CUSTOMERS;
SELECT 'UT-03: Validation rejects' AS test, CASE WHEN COUNT(*) = 5 THEN 'PASS' ELSE 'FAIL' END FROM DE_POC.PUBLIC.QUARANTINE_CUSTOMERS WHERE REJECTION_RULE IN ('MANDATORY_FIELD', 'BUSINESS_RULE');
SELECT 'UT-04: Duplicate rejects' AS test, CASE WHEN COUNT(*) = 2 THEN 'PASS' ELSE 'FAIL' END FROM DE_POC.PUBLIC.QUARANTINE_CUSTOMERS WHERE REJECTION_RULE = 'DUPLICATE_INTRA_BATCH';
SELECT 'UT-05: Dedup keeps latest' AS test, CASE WHEN LAST_NAME = 'Gugale-Updated' THEN 'PASS' ELSE 'FAIL' END FROM DE_POC.PUBLIC.CUSTOMERS_V2 WHERE CUSTOMER_ID = 'C101';
SELECT 'UT-06: No NULLs' AS test, CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END FROM DE_POC.PUBLIC.CUSTOMERS_V2 WHERE CUSTOMER_ID IS NULL OR FIRST_NAME IS NULL OR LAST_NAME IS NULL OR EMAIL IS NULL;
SELECT 'UT-07: Unique keys' AS test, CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END FROM (SELECT CUSTOMER_ID FROM DE_POC.PUBLIC.CUSTOMERS_V2 GROUP BY CUSTOMER_ID HAVING COUNT(*) > 1);
SELECT 'UT-08: Rejection reasons' AS test, CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END FROM DE_POC.PUBLIC.QUARANTINE_CUSTOMERS WHERE REJECTION_REASON IS NULL OR REJECTION_REASON = '';
SELECT 'UT-09: Audit trail' AS test, CASE WHEN COUNT(DISTINCT PHASE) = 5 THEN 'PASS' ELSE 'FAIL' END FROM DE_POC.PUBLIC.PIPELINE_AUDIT_LOG WHERE BATCH_ID = (SELECT MAX(BATCH_ID) FROM DE_POC.PUBLIC.PIPELINE_AUDIT_LOG);
SELECT 'DQ-01: Reconciliation' AS test, CASE WHEN (SELECT COUNT(*) FROM DE_POC.PUBLIC.STG_CUSTOMERS_V2) = (SELECT COUNT(*) FROM DE_POC.PUBLIC.CUSTOMERS_V2) + (SELECT COUNT(*) FROM DE_POC.PUBLIC.QUARANTINE_CUSTOMERS) THEN 'PASS' ELSE 'FAIL' END;
SELECT 'DQ-02: Idempotency' AS test, CASE WHEN COUNT(*) = 5 THEN 'PASS' ELSE 'FAIL' END FROM DE_POC.PUBLIC.CUSTOMERS_V2;
