-- Create tables for customer data ingestion pipeline
-- Co-authored with CoCo

USE DATABASE DE_POC;
USE SCHEMA PUBLIC;

-- Stage: internal stage for source CSV files
CREATE STAGE IF NOT EXISTS CUSTOMER_DATA_STAGE;

-- Raw staging table: landing zone for COPY INTO
CREATE TABLE IF NOT EXISTS RAW_CUSTOMER_STAGING (
    CUSTOMER_ID   VARCHAR(50),
    FIRST_NAME    VARCHAR(100),
    LAST_NAME     VARCHAR(100),
    EMAIL         VARCHAR(255),
    PHONE         VARCHAR(50),
    ADDRESS       VARCHAR(500),
    CITY          VARCHAR(100),
    STATE         VARCHAR(50),
    ZIP_CODE      VARCHAR(20),
    COUNTRY       VARCHAR(100),
    CREATED_DATE  VARCHAR(30),
    UPDATED_DATE  VARCHAR(30),
    _SOURCE_FILE  VARCHAR(500),
    _LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Enable change tracking for stream-based CDC
ALTER TABLE RAW_CUSTOMER_STAGING SET CHANGE_TRACKING = TRUE;

-- Stream on staging table for incremental processing (AC-1, AC-6)
CREATE STREAM IF NOT EXISTS RAW_CUSTOMER_STREAM
    ON TABLE RAW_CUSTOMER_STAGING
    APPEND_ONLY = TRUE;

-- Target analytics table (AC-7)
CREATE TABLE IF NOT EXISTS CUSTOMER (
    CUSTOMER_ID   VARCHAR(50) NOT NULL,
    FIRST_NAME    VARCHAR(100),
    LAST_NAME     VARCHAR(100),
    EMAIL         VARCHAR(255),
    PHONE         VARCHAR(50),
    ADDRESS       VARCHAR(500),
    CITY          VARCHAR(100),
    STATE         VARCHAR(50),
    ZIP_CODE      VARCHAR(20),
    COUNTRY       VARCHAR(100),
    CREATED_DATE  TIMESTAMP_NTZ,
    UPDATED_DATE  TIMESTAMP_NTZ,
    _LOAD_ID      VARCHAR(36),
    _SOURCE_FILE  VARCHAR(500),
    _LOADED_AT    TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    _UPDATED_AT   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_CUSTOMER PRIMARY KEY (CUSTOMER_ID)
);

-- Load tracking table (AC-4)
CREATE TABLE IF NOT EXISTS CUSTOMER_LOAD_TRACKING (
    LOAD_ID            VARCHAR(36) NOT NULL,
    SOURCE_FILE        VARCHAR(500),
    LOAD_TIMESTAMP     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RECORDS_STAGED     NUMBER DEFAULT 0,
    RECORDS_VALID      NUMBER DEFAULT 0,
    RECORDS_REJECTED   NUMBER DEFAULT 0,
    RECORDS_INSERTED   NUMBER DEFAULT 0,
    RECORDS_UPDATED    NUMBER DEFAULT 0,
    RECORDS_DUPLICATE  NUMBER DEFAULT 0,
    PROCESSING_STATUS  VARCHAR(20) DEFAULT 'PENDING',
    ERROR_MESSAGE      VARCHAR(2000),
    COMPLETED_AT       TIMESTAMP_NTZ,
    CONSTRAINT PK_LOAD_TRACKING PRIMARY KEY (LOAD_ID)
);

-- Error log table (AC-3, AC-5)
CREATE TABLE IF NOT EXISTS CUSTOMER_ERROR_LOG (
    ERROR_ID        NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    LOAD_ID         VARCHAR(36),
    SOURCE_FILE     VARCHAR(500),
    CUSTOMER_ID     VARCHAR(50),
    RECORD_CONTENT  VARIANT,
    ERROR_REASON    VARCHAR(1000),
    ERROR_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_CUSTOMER_ERROR_LOG PRIMARY KEY (ERROR_ID)
);
