-- DDL setup for automated customer data ingestion pipeline (DEPOC-32)
-- Co-authored with CoCo

-- File format for CSV customer data
CREATE OR REPLACE FILE FORMAT DE_POC.PUBLIC.CUSTOMER_CSV_FORMAT
  TYPE = 'CSV'
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  NULL_IF = ('', 'NULL', 'null')
  EMPTY_FIELD_AS_NULL = TRUE
  ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;

-- Raw staging table for landing data from stage
CREATE OR REPLACE TABLE DE_POC.PUBLIC.RAW_CUSTOMER_STAGING (
    CUSTOMER_ID         VARCHAR(50),
    FIRST_NAME          VARCHAR(100),
    LAST_NAME           VARCHAR(100),
    EMAIL               VARCHAR(255),
    PHONE               VARCHAR(50),
    ADDRESS             VARCHAR(500),
    CITY                VARCHAR(100),
    STATE               VARCHAR(50),
    ZIP_CODE            VARCHAR(20),
    COUNTRY             VARCHAR(100),
    CREATED_DATE        VARCHAR(30),
    UPDATED_DATE        VARCHAR(30),
    _SOURCE_FILE        VARCHAR(500),
    _LOAD_TIMESTAMP     TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP()
);

-- Target customer table (deduplicated, validated)
CREATE OR REPLACE TABLE DE_POC.PUBLIC.CUSTOMER (
    CUSTOMER_ID         VARCHAR(50)    NOT NULL,
    FIRST_NAME          VARCHAR(100),
    LAST_NAME           VARCHAR(100),
    EMAIL               VARCHAR(255),
    PHONE               VARCHAR(50),
    ADDRESS             VARCHAR(500),
    CITY                VARCHAR(100),
    STATE               VARCHAR(50),
    ZIP_CODE            VARCHAR(20),
    COUNTRY             VARCHAR(100),
    CREATED_DATE        TIMESTAMP_NTZ,
    UPDATED_DATE        TIMESTAMP_NTZ,
    _LOAD_ID            VARCHAR(36),
    _SOURCE_FILE        VARCHAR(500),
    _LOADED_AT          TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP(),
    _UPDATED_AT         TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_CUSTOMER PRIMARY KEY (CUSTOMER_ID)
);

-- Load tracking table (batch metadata)
CREATE OR REPLACE TABLE DE_POC.PUBLIC.CUSTOMER_LOAD_TRACKING (
    LOAD_ID             VARCHAR(36)    NOT NULL,
    SOURCE_FILE         VARCHAR(500),
    LOAD_TIMESTAMP      TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP(),
    RECORDS_STAGED      NUMBER         DEFAULT 0,
    RECORDS_VALID       NUMBER         DEFAULT 0,
    RECORDS_REJECTED    NUMBER         DEFAULT 0,
    RECORDS_INSERTED    NUMBER         DEFAULT 0,
    RECORDS_UPDATED     NUMBER         DEFAULT 0,
    RECORDS_DUPLICATE   NUMBER         DEFAULT 0,
    PROCESSING_STATUS   VARCHAR(20)    DEFAULT 'PENDING',
    ERROR_MESSAGE       VARCHAR(2000),
    COMPLETED_AT        TIMESTAMP_NTZ,
    CONSTRAINT PK_LOAD_TRACKING PRIMARY KEY (LOAD_ID)
);

-- Error log for rejected/invalid records
CREATE OR REPLACE TABLE DE_POC.PUBLIC.CUSTOMER_ERROR_LOG (
    ERROR_ID            NUMBER AUTOINCREMENT,
    LOAD_ID             VARCHAR(36),
    SOURCE_FILE         VARCHAR(500),
    CUSTOMER_ID         VARCHAR(50),
    RECORD_CONTENT      VARIANT,
    ERROR_REASON        VARCHAR(1000),
    ERROR_TIMESTAMP     TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_CUSTOMER_ERROR_LOG PRIMARY KEY (ERROR_ID)
);

-- CDC stream on staging for incremental processing
CREATE OR REPLACE STREAM DE_POC.PUBLIC.RAW_CUSTOMER_STREAM
  ON TABLE DE_POC.PUBLIC.RAW_CUSTOMER_STAGING
  APPEND_ONLY = TRUE;

-- Scheduled task: runs every 4 hours
CREATE OR REPLACE TASK DE_POC.PUBLIC.TASK_INGEST_CUSTOMER_DATA
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = 'USING CRON 0 */4 * * * America/New_York'
AS
  CALL DE_POC.PUBLIC.SP_INGEST_CUSTOMER_DATA();